# Form implementation generated from reading ui file 'views/find_and_replace.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FindAndReplace(object):
    def setupUi(self, FindAndReplace):
        FindAndReplace.setObjectName("FindAndReplace")
        FindAndReplace.resize(502, 157)
        self.gridLayout = QtWidgets.QGridLayout(FindAndReplace)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FindAndReplace)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.findText = QtWidgets.QLineEdit(FindAndReplace)
        self.findText.setObjectName("find_text")
        self.gridLayout.addWidget(self.findText, 0, 1, 1, 1)
        self.findNextBtn = QtWidgets.QPushButton(FindAndReplace)
        self.findNextBtn.setDefault(True)
        self.findNextBtn.setObjectName("findNextBtn")
        self.gridLayout.addWidget(self.findNextBtn, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(FindAndReplace)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.replaceText = QtWidgets.QLineEdit(FindAndReplace)
        self.replaceText.setObjectName("replace_text")
        self.gridLayout.addWidget(self.replaceText, 1, 1, 1, 1)
        self.replaceBtn = QtWidgets.QPushButton(FindAndReplace)
        self.replaceBtn.setEnabled(False)
        self.replaceBtn.setObjectName("replaceBtn")
        self.gridLayout.addWidget(self.replaceBtn, 1, 2, 1, 1)
        self.regex = QtWidgets.QRadioButton(FindAndReplace)
        self.regex.setChecked(True)
        self.regex.setObjectName("regex")
        self.gridLayout.addWidget(self.regex, 2, 0, 1, 1)
        self.matchCase = QtWidgets.QCheckBox(FindAndReplace)
        self.matchCase.setEnabled(False)
        self.matchCase.setObjectName("matchCase")
        self.gridLayout.addWidget(self.matchCase, 2, 1, 1, 1)
        self.replaceAllBtn = QtWidgets.QPushButton(FindAndReplace)
        self.replaceAllBtn.setEnabled(False)
        self.replaceAllBtn.setObjectName("replaceAllBtn")
        self.gridLayout.addWidget(self.replaceAllBtn, 2, 2, 1, 1)
        self.simple = QtWidgets.QRadioButton(FindAndReplace)
        self.simple.setEnabled(False)
        self.simple.setObjectName("simple")
        self.gridLayout.addWidget(self.simple, 3, 0, 1, 1)
        self.matchWord = QtWidgets.QCheckBox(FindAndReplace)
        self.matchWord.setEnabled(False)
        self.matchWord.setObjectName("matchWord")
        self.gridLayout.addWidget(self.matchWord, 3, 1, 1, 1)
        self.cancelBtn = QtWidgets.QPushButton(FindAndReplace)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 3, 2, 1, 1)

        self.retranslateUi(FindAndReplace)
        self.cancelBtn.clicked.connect(FindAndReplace.close)
        QtCore.QMetaObject.connectSlotsByName(FindAndReplace)

    def retranslateUi(self, FindAndReplace):
        _translate = QtCore.QCoreApplication.translate
        FindAndReplace.setWindowTitle(_translate("FindAndReplace", "Find and Replace"))
        self.label.setText(_translate("FindAndReplace", "Find:"))
        self.findNextBtn.setText(_translate("FindAndReplace", "Find All"))
        self.label_2.setText(_translate("FindAndReplace", "Replace:"))
        self.replaceBtn.setText(_translate("FindAndReplace", "Replace Next"))
        self.regex.setText(_translate("FindAndReplace", "RegEx"))
        self.matchCase.setText(_translate("FindAndReplace", "Match Case"))
        self.replaceAllBtn.setText(_translate("FindAndReplace", "Replace All"))
        self.simple.setText(_translate("FindAndReplace", "Simple"))
        self.matchWord.setText(_translate("FindAndReplace", "Match Word"))
        self.cancelBtn.setText(_translate("FindAndReplace", "Cancel"))
