# Form implementation generated from reading ui file 'views/rename_header.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Rename_header_dialog(object):
    def setupUi(self, Rename_header_dialog):
        Rename_header_dialog.setObjectName("Rename_header_dialog")
        Rename_header_dialog.resize(383, 73)
        self.verticalLayout = QtWidgets.QVBoxLayout(Rename_header_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Rename_header_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Rename_header_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientations.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButtons.Cancel|QtWidgets.QDialogButtonBox.StandardButtons.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Rename_header_dialog)
        self.buttonBox.accepted.connect(Rename_header_dialog.accept)
        self.buttonBox.rejected.connect(Rename_header_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Rename_header_dialog)

    def retranslateUi(self, Rename_header_dialog):
        _translate = QtCore.QCoreApplication.translate
        Rename_header_dialog.setWindowTitle(_translate("Rename_header_dialog", "Rename Header"))
